version: '3'

services:
  app:
    container_name: mongo-recipe
    restart: always
    build: .
    ports:
      - '5500:55000'
    external_links:
      - mongo

    mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./:/usr/src/app
      ports:
        - '27012:27017'

  